#spring:
#  application:
#    name: product-service
#  data:
#    mongodb:
#      host: localhost
#      port: 27017
#      database: product_service_db
#      authentication-database: admin
#      auto-index-creation: true